epoch: 11

LearningRate:
  base_lr: 0.00005
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [5, 8]
  - !LinearWarmup
    start_factor: 0.01
    steps: 1000

OptimizerBuilder:
  clip_grad_by_norm: 1.0
  optimizer:
    type: AdamW
    weight_decay: 0.0001
