_BASE_: [
  '../datasets/voc.yml',
  '../runtime.yml',
  '_base_/optimizer_30e.yml',
  '_base_/ssdlite_mobilenet_v3_small_320.yml',
  '_base_/ssdlite320_reader.yml',
]
weights: output/ssdlite_mobilenet_v3_small_320_coco/model_final
